### ISSUE TITLE
After hover, and mouseoff, "Cannot read property 'removeAttribute' of null

### ISSUE THREAD

**Issue by ssmith353** [metal/metal-tooltip#8]
After mouseoff of the tooltip, this error is thrown. 

> bundle.nocsf.js?browserId=other&minifierType=js&languageId=en_US&b=7010&t=249:1059 Uncaught TypeError: Cannot read property 'removeAttribute' of null
>     at Tooltip.syncAlignElement (bundle.nocsf.js?browserId=other&minifierType=js&languageId=en_US&b=7010&t=249:1059)
>     at Tooltip.fireStateKeyChange_ (bundle.nocsf.js?browserId=other&minifierType=js&languageId=en_US&b=7010&t=249:251)
>     at Tooltip.syncStateFromChanges_ (bundle.nocsf.js?browserId=other&minifierType=js&languageId=en_US&b=7010&t=249:254)
>     at Tooltip.handleStateChanged_ (bundle.nocsf.js?browserId=other&minifierType=js&languageId=en_US&b=7010&t=249:251)
>     at Tooltip.emit (bundle.nocsf.js?browserId=other&minifierType=js&languageId=en_US&b=7010&t=249:185)
>     at State.emitBatchEvent_ (bundle.nocsf.js?browserId=other&minifierType=js&languageId=en_US&b=7010&t=249:284)
>     at run (bundle.nocsf.js?browserId=other&minifierType=js&languageId=en_US&b=7010&t=249:121)
>     at runIfPresent (bundle.nocsf.js?browserId=other&minifierType=js&languageId=en_US&b=7010&t=249:122)
>     at onGlobalMessage (bundle.nocsf.js?browserId=other&minifierType=js&languageId=en_US&b=7010&t=249:124)

**Comment by eduardolundgren** [comment]
@pragmaticivan Is that the same error you had on dashboard?

**Comment by pragmaticivan** [comment]
@eduardolundgren nop. it was related with the style property.

**Comment by pragmaticivan** [comment]
@ssmith353 can you post the version of metal-tooltip and metaljs you're using in your project?

**Comment by ssmith353** [comment]
"metal-tooltip" : "2.0.1",
"metal": "2.5.2"

**Comment by pragmaticivan** [comment]
@ssmith353 can you post here how you're creating the instance of this component?

**Comment by ssmith353** [comment]
Within the render method of our form component we have: 

				<div class="tooltip-wrapper">
					<Tooltip
						delay="[300, 150]"
						elementClasses={'fade'}
						position={Tooltip.Align.Right}
						selector={'[data-title]'}
						visible={false}
					/>
				</div>

with certain form fields containing this 

<span class="tooltip-icon" data-title={tooltipLabel} />

**Comment by fernandosouza** [comment]
sure @eduardolundgren. I will take a look on it urgently.

**Comment by fernandosouza** [comment]
Hello, @ssmith353. Are you using Metal Router in the project?

**Comment by ssmith353** [comment]
@fernandosouza see our attached package.json dependencies. 

```
		"immutable": "3.8.1",
		"metal": "2.5.2",
		"metal-ajax": "2.0.3",
		"metal-alert": "2.0.1",
		"metal-component": "2.5.5",
		"metal-debounce": "2.0.0",
		"metal-dom": "2.5.3",
		"metal-events": "2.5.3",
		"metal-incremental-dom": "2.5.7",
		"metal-jsx": "2.5.8",
		"metal-path-parser": "1.0.3",
		"metal-position": "2.0.0",
		"metal-promise": "2.0.1",
		"metal-react": "2.0.0",
		"metal-redux": "2.0.0",
		"metal-router": "3.0.8",
		"metal-soy": "2.5.7",
		"metal-state": "2.5.3",
		"metal-structs": "1.0.1",
		"metal-tooltip" : "2.0.1",
		"metal-uri": "2.0.2",
		"metal-useragent": "2.1.1",
		"react": "15.4.0",
		"react-dom": "15.4.0",
		"react-dropzone": "3.6.0",
		"react-select": "^1.0.0-rc.2",
		"redux": "3.6.0",
		"redux-immutable": "3.0.8",
		"redux-thunk": "2.1.0",
		"senna": "2.0.4",
		"string-sub": "0.0.1"
```

**Comment by fernandosouza** [comment]
I've asked you about the `metal-router` because we're trying to figure out if there's something related to the error. I couldn't reproduce it by using only the component.

I've noticed you aren't using the latest version of the modules. Could you update and check if the error is still there, please?

"metal": "2.5.19",
"metal-ajax": "2.0.3",
"metal-alert": "2.0.1",
"metal-component": "2.5.18",
"metal-debounce": "2.0.0",
"metal-dom": "2.5.18",
"metal-events": "2.5.18",
"metal-incremental-dom": "2.5.19",
"metal-jsx": "2.5.19",
"metal-path-parser": "1.0.3",
"metal-position": "2.0.0",
"metal-promise": "2.0.1",
"metal-react": "2.0.0",
"metal-redux": "2.0.1",
"metal-router": "3.1.0",
"metal-soy": "2.5.19",
"metal-state": "2.5.18",
"metal-structs": "1.0.1",
"metal-tooltip" : "2.0.2",
"metal-uri": "2.0.2",
"metal-useragent": "2.1.2",

**Comment by eduardolundgren** [comment]
The issue here seems likely because the new lifecyle. When a parent component of a tooltip gets `rerendered` its child also gets `rerendered` and the tooltip has asynchronous behavior that were `clearTimeout` on dispose only and need to be cleared on `rerendered` as well. This might fix it.

**Comment by eduardolundgren** [comment]
@ssmith353 we are going to apply the fix on tooltip still

**Comment by fernandosouza** [comment]
Thanks for your feedback, @ssmith353. 

That seems to occur in certain circumstances because I could not reproduce this error even rendering the tooltip as a subcomponent.

**Comment by eduardolundgren** [comment]
@fernandosouza It happens if the parent component re-render while the tooltip is visible.

**Comment by ssmith353** [comment]
hey guys, just implemented the new version in our project, and is fixed! Thanks!
